"""Rigid cyclic six-note templates and the residual discovery inventory.

The thirteen seeds are exact pairs, not equivalence classes identifying unit
multiples.  Unit multiplication only organizes or transports certificates.
No assertion here exhausts all signed matchings of all six-point pairs.
"""
from __future__ import annotations
import argparse
from collections import Counter
from itertools import combinations
import json
from math import gcd
from pathlib import Path
import time
from sympy import ZZ
from sympy.polys.matrices import DomainMatrix
from sympy.polys.matrices.normalforms import smith_normal_decomp
from six_explore import canon, icv
from six_shadow import anchored_vector, matching_count, matching_matrices

ROOT = Path(__file__).resolve().parents[1]
SEEDS = (
 (17,(0,1,2,3,8,12),(0,1,2,6,7,9)),
 (19,(0,1,2,3,6,10),(0,1,2,4,5,11)),
 (21,(0,1,2,4,7,14),(0,1,3,7,8,10)),
 (21,(0,1,2,5,6,15),(0,1,2,6,7,10)),
 (21,(0,1,3,7,10,15),(0,1,4,7,14,16)),
 (23,(0,1,2,3,7,17),(0,1,2,4,17,18)),
 (24,(0,1,2,5,7,16),(0,1,2,6,9,11)),
 (27,(0,1,2,3,7,19),(0,1,2,3,8,12)),
 (27,(0,1,2,6,19,22),(0,1,3,17,21,22)),
 (28,(0,1,2,4,12,23),(0,1,3,5,11,12)),
 (30,(0,1,2,6,19,22),(0,1,3,9,13,14)),
 (30,(0,1,3,5,12,25),(0,1,6,9,11,13)),
 (31,(0,1,2,5,11,19),(0,1,2,6,20,23)),
)


def transported_pair(seed_index, n, t):
    """Homomorphic image of seed; t may have any order dividing q.

    Return actual T/I representatives, or None when a collision or a trivial
    rigid equivalence prevents a six-note Z-pair.
    """
    q,a,b=SEEDS[seed_index]
    if n < 1 or (q*t)%n:
        raise ValueError("require q*t = 0 modulo n")
    aa,bb={t*x%n for x in a},{t*x%n for x in b}
    if len(aa)!=6 or len(bb)!=6:
        return None
    aa,bb=canon(aa,n),canon(bb,n)
    return tuple(sorted((aa,bb))) if aa!=bb else None


def seed_edges(n):
    """Every distinct T/I pair generated by all 13 seeds in Z_n."""
    edges={}
    for i,(q,_,_) in enumerate(SEEDS):
        for t in range(0,n,n//gcd(q,n)):
            pair=transported_pair(i,n,t)
            if pair is not None:
                edges.setdefault(pair,[]).append(dict(seed=i+1,t=t,source_modulus=q))
    return edges


def primitive_key(a,b,n):
    """Organizational unit/inflation key; retain the input endpoints elsewhere."""
    g=gcd(n,*a,*b);q=n//g
    aa,bb=tuple(x//g for x in a),tuple(x//g for x in b)
    key=min(tuple(sorted((canon([u*x%q for x in aa],q),
                          canon([u*x%q for x in bb],q))))
            for u in range(1,q) if gcd(u,q)==1)
    return q,key


def residual_inventory(nmin=12,nmax=60):
    rows=[]; groups={}
    for n in range(nmin,nmax+1):
        inventory=json.loads((ROOT/f"results/2026-09-30-six-inventory/n{n}.json").read_text())
        shapes=json.loads((ROOT/f"results/2026-09-30-six-shell/n{n}.json").read_text())
        shape_edges={tuple(sorted((tuple(e['x']),tuple(e['y'])))) for e in shapes['pairs']}
        rigid=seed_edges(n);gaps=[];remaining=[]
        for f in inventory['families']:
            members=list(map(tuple,f['members']));parent={a:a for a in members}
            def find(a):
                while parent[a]!=a:a=parent[a]
                return a
            edges={tuple(sorted((tuple(e['a']),tuple(e['b']))))
                   for e in f['strict_edges']+f['bloom_edges']}
            edges.update(pair for pair in combinations(members,2) if pair in shape_edges)
            for a,b in edges:parent[find(a)]=find(b)
            for a,b in combinations(members,2):
                if find(a)!=find(b):
                    key=primitive_key(a,b,n)
                    cert=dict(n=n,a=a,b=b,seed_certificates=rigid.get((a,b),[]))
                    groups.setdefault(key,[]).append(cert);gaps.append(cert)
            for a,b in combinations(members,2):
                if (a,b) in rigid:parent[find(a)]=find(b)
            if len({find(a) for a in members})>1:remaining.append(members)
        rows.append(dict(n=n,residual_pairs=len(gaps),remaining_families=len(remaining),
                         gaps=gaps,remaining=remaining))
    grouped=[dict(q=q,a=pair[0],b=pair[1],occurrences=members)
             for (q,pair),members in sorted(groups.items())]
    return dict(status="COMPUTED-UNVALIDATED discovery labels; exact certificates independently checkable",
                nmin=nmin,nmax=nmax,groups=grouped,by_n=rows)


def smith_templates():
    records=[];start=time.monotonic()
    for i,(q,a,b) in enumerate(SEEDS,1):
        v=anchored_vector(a,b,q);certs=[];signatures=Counter()
        for m,labels in matching_matrices(a,b,q):
            dd,uu,vv=smith_normal_decomp(DomainMatrix.from_Matrix(m).convert_to(ZZ))
            d,u,w=dd.to_Matrix(),uu.to_Matrix(),vv.to_Matrix()
            assert u*m*w==d
            diag=tuple(int(d[j,j]) for j in range(10));signatures[diag]+=1
            assert diag==(1,)*9+(q,), (i,diag)
            col=[int(w[j,9]) for j in range(10)]
            scalar=pow(col[0],-1,q)
            assert tuple(x*scalar%q for x in col)==v
            certs.append(dict(labels=labels,matrix=[[int(x) for x in r] for r in m.tolist()],
                              left=[[int(x) for x in r] for r in u.tolist()],
                              right=[[int(x) for x in r] for r in w.tolist()],
                              diagonal=diag,generator=col,normalizing_scalar=scalar))
        assert len(certs)==matching_count(a,b,q)
        projections=[]
        for d in range(1,q+1):
            if q%d==0:
                pair=transported_pair(i-1,d,1)
                if pair is not None:projections.append(dict(order=d,a=pair[0],b=pair[1]))
        row=dict(seed=i,q=q,a=a,b=b,matchings=len(certs),certificates=certs,
                 nontrivial_image_orders=[x['order'] for x in projections],projections=projections)
        records.append(row)
        print(i,q,len(certs),row['nontrivial_image_orders'],round(time.monotonic()-start,3),flush=True)
    return dict(status="COMPUTED-UNVALIDATED until independent matrix and completeness audit",
                seeds=records,total_matchings=sum(x['matchings'] for x in records),
                seconds=round(time.monotonic()-start,3))


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',type=Path,default=ROOT/'results/2026-09-30-six-templates')
    args=parser.parse_args();args.out.mkdir(parents=True,exist_ok=True)
    for name,payload in [('inventory',residual_inventory()),('smith',smith_templates())]:
        target=args.out/f'{name}.json';temp=target.with_suffix('.tmp')
        temp.write_text(json.dumps(payload,sort_keys=True)+'\n');temp.replace(target)
    print('saved',args.out,flush=True)

if __name__=='__main__':main()
